# ETL Pipeline Configuration
# Social Media Comments Analysis with Gemini AI

# Data paths configuration
data:
  base_path: "."
  raw_path: "data/raw"
  processed_path: "data/processed"
  output_path: "data/output"
  logs_path: "logs"

# Input file names (legacy compatibility)
input_files:
  comments: "comments.json"
  classified: "classified.json"
  replies: "replies.json"

# Output file configuration
output_files:
  csv: "social_media_analysis.csv"
  excel: "social_media_analysis.xlsx"
  pdf: "social_media_report.pdf"
  metadata: "pipeline_metadata.json"

# Gemini AI configuration
gemini:
  enabled: true
  batch_size: 50
  delay_between_requests: 1.0
  max_retries: 3
  # Note: API key should be set via environment variable in production
  # export GEMINI_API_KEY="your-api-key-here"

# Pipeline settings
pipeline:
  create_sample_data: false
  preservation_rate_threshold: 85.0
  max_pdf_rows: 100
  max_text_length: 100

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_logging: true
  console_logging: true